apiVersion: v1
kind: Service
metadata:
  name: donaton-db
  namespace: donaton
spec:
  selector:
    app: donaton-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

