apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: donaton
type: Opaque
stringData:
  DATABASE_USER: "donaton"
  DATABASE_PASSWORD: "Duoc2026"
  DATABASE_NAME: "donaton_db"
  DATABASE_HOST: "db-mysql"
  DATABASE_PORT: "3306"
  ROOT_PASSWORD: "root2025"
