apiVersion: v1
kind: Secret
metadata:
  name: prisma-secret
  namespace: donaton
type: Opaque
stringData:
  DATABASE_URL: "mysql://donaton:Duoc2026@donaton-db:3306/donaton_db"
  SHADOW_DATABASE_URL: "mysql://donaton:Duoc2026@donaton-db:3306/shadow_donaton_db"
